# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImageName: 'ubuntu-latest'

variables:
  agent.disablelogplugin.TestResultLogPlugin: 'false'
  skipComponentGovernanceDetection: 'true'

steps:
- script: |
    docker build -t myimg3 .
    docker run myimg3